# Generated by Django 5.2.2 on 2025-06-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrow',
            options={'verbose_name': 'Mượn trả', 'verbose_name_plural': 'Mượn trả'},
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13, unique=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='status',
            field=models.CharField(choices=[('borrowed', 'Đang mượn'), ('returned', 'Đã trả'), ('overdue', 'Quá hạn')], default='borrowed', max_length=10, verbose_name='Trạng thái'),
        ),
    ]
